### ISSUE TITLE
WMS mapalgebra layer’s rendering crashes for layer in other SRS than WebMercator

### ISSUE THREAD

**Issue by micpilon** [geotrellis/geotrellis-server#258] opened 2020-05-11 20:34 UTC
I am having issues related to serving mapalgebra computed layers such as hillshade, slope and aspect with a WMS when the source layer has a spatial reference system different than WebMercator. 
Browser throws: `Layer (hrdtm-hillshade) not found or CRS (EPSG:3857) not supported`
Console throws: `ERROR geotrellis.server.ogc.wms.WmsView - java.lang.RuntimeException: Tile is too small to get surface values. (1, 1)`
Here's a more detailed stack trace
![stacktrace](https://user-images.githubusercontent.com/46534635/81608159-cf97b600-93a3-11ea-9de5-70021f40e8c7.png)

The source layer behind the mapalgebra computation (type = "rastersourceconf") does render correctly. Also, the WCS displays these mapalgebra layers correctly spatially in a GIS, which leads to think that this is mostly a rendering problem. 

I can provide you with samples soon.

Thanks!

**Comment by pomadchin** [comment] 2020-05-11 20:49
Hi @micpilon! Thanks for catching that; the example would be very useful indeed

**Comment by pomadchin** [comment] 2020-05-13 23:03
A small update: the layer read is for some reason empty. There is a bug in GeoTrellisRasterSources that could stitch an empty query result into a large raster (see https://github.com/locationtech/geotrellis/pull/3240) which caused a bit unreadble error messages. 
In general it looks like the ingested layer is _empty_. Its metadata (bounds / extent / crs) can be incorrect.

**Comment by pomadchin** [comment] 2020-05-14 23:05
It looks like the problem is in the zFactor set for the hillshade operation. Try to set it to smth like `9.166226027378224E-5` for this dataset!

**Comment by pomadchin** [comment] 2020-05-21 21:31
The issue was that the histogram used the min cellSize available for the layer, and such cellSize could be too small to calculate the hillshade. 

This PR https://github.com/geotrellis/geotrellis-server/pull/261 should fix it: it tries to select the still the minCellSize but it selects the layer that has enough of pixles to compute the histogram.

**Comment by micpilon** [comment] 2020-05-27 19:43
PR #261 indeed fixes the problem. Thanks @pomadchin !

**Comment by pomadchin** [comment] 2020-05-27 20:12
@micpilon thanks for reviewing it! closing!

**Closed by pomadchin** 2020-05-27 20:12 UTC
Labels: bug
